// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDaTZh5DbhCZe7JUhRQ2e-MjoOjRviEhyY',
    appId: '1:1041989128769:web:abd81795c6f22c4a3c6cc0',
    messagingSenderId: '1041989128769',
    projectId: 'event-app-2414b',
    authDomain: 'event-app-2414b.firebaseapp.com',
    storageBucket: 'event-app-2414b.firebasestorage.app',
    measurementId: 'G-S975F58N13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHobiydVd4Y8tt_VHtfyHtGg5ukf-P4gQ',
    appId: '1:1041989128769:android:4962a9ec640c1d023c6cc0',
    messagingSenderId: '1041989128769',
    projectId: 'event-app-2414b',
    storageBucket: 'event-app-2414b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA8gaHoP3Tc7SQ5LmKPmrJ7h_g7FAVn06E',
    appId: '1:1041989128769:ios:27ce4ff9220a24b33c6cc0',
    messagingSenderId: '1041989128769',
    projectId: 'event-app-2414b',
    storageBucket: 'event-app-2414b.firebasestorage.app',
    iosBundleId: 'com.example.untitled15',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA8gaHoP3Tc7SQ5LmKPmrJ7h_g7FAVn06E',
    appId: '1:1041989128769:ios:27ce4ff9220a24b33c6cc0',
    messagingSenderId: '1041989128769',
    projectId: 'event-app-2414b',
    storageBucket: 'event-app-2414b.firebasestorage.app',
    iosBundleId: 'com.example.untitled15',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDaTZh5DbhCZe7JUhRQ2e-MjoOjRviEhyY',
    appId: '1:1041989128769:web:0d586384a11d62ef3c6cc0',
    messagingSenderId: '1041989128769',
    projectId: 'event-app-2414b',
    authDomain: 'event-app-2414b.firebaseapp.com',
    storageBucket: 'event-app-2414b.firebasestorage.app',
    measurementId: 'G-JB5E4K5EV9',
  );
}
